version: '3'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "80:7777"
    depends_on:
      - postgres
      - redis
    command: ["npm", "start"]
