version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    networks:
      - overlay 
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
       - mysql:/var/lib/mysql
    networks:
       - overlay

volumes:
  mysql:

networks:
  overlay:
